spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/expense_tracker
server:
  port: '1001'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
