spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/orders
    password: admin
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '1002'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
